### PR TITLE
Adjust the alignment and sort key in output results.

### PR DESCRIPTION
**Pull request by xxconn**
Just for recommendation.

### CODE REVIEW

**Comment by TheWitness** [comment]
Can you upload a before and after.  I'm a bit persnickety on column alignment.  Left aligned on the left of the table, right aligned on the right, and center anywhere except the left and right most.

**Comment by xxconn** [comment]
For reference

Before
Before

After
After

**Comment by TheWitness** [comment]
Okay, I'm good with that.  Let me know when it's ready to merge.

**Comment by xxconn** [comment]
Could you please merge this PR?  I will add some new features like manually add vlans to scan or skip and collect the vm’s trunking port mac addresses.

**Comment by TheWitness** [comment]
@xxconn, if you would like to join us on Slack, reach out in email to thewitness at cacti dot net.  Use the email you would like to use for Slack.

**Pull request merged**
