### PR TITLE
Adding New 802.1x Scanning function and IP Scanning function (dhcp snooping)

### PR DESCRIPTION
**Pull request by jpobeda**
Hi Jimmy,

There are a bunch of things here.

* 81ef4b3 => adding a new column to IP Address view.

* c38bd85 => Fixing OUI Database import. When it fails it actually carries on and remove all the existing records. 1 comment here, are you able to add an option to use a proxy? Pretty much any organization now days uses proxy in 1 way or another.

Sorry for the mess, It's clear I'm not a dev :/ and it's a lot to review.

* dfb1c6a => Can you please help me to show 'status' reference instead of the code? You can find the reference on mactrack_view_dot1x.php:172

Can you also have a look at mactrack_cisco.php for:

```
get_cisco_dhcpsnooping_table around line 574 , i've put some comments.
get_cisco_dot1x_table around line 667, i've put some comments.
```

Don't hesitate to ask since there are a lot of ugly commits.

### CODE REVIEW

**Comment by cigamit** [comment]
I'm mega busy right now.  Be free in a week or so.  Please be patient.

**Comment by jpobeda** [comment]
Thanks Jimmy, no rush here. I was suspecting that the SQL queries weren't very fast so I've enabled mysql slow queries and attached output. I was hoping you can help me to improve them before committing the PR.

It seems to be the second left join to mac_track_interfaces.

[mt_slow_queries.txt](https://github.com/Cacti/plugin_mactrack/files/1429282/mt_slow_queries.txt)

You'll see site 2 which is the one with more devices compared to the others.

Thanks

**Comment by jpobeda** [comment]
Adding "ifIndex" index to table mac_track_interfaces made the queries a lot faster.

**Comment by cigamit** [comment]
Javier,  Can you fix that syntax error in mactrack_functions.php?  I'll merge afterwards.  I'm trying to keep up.  Just too busy at the moment.

**Comment by jpobeda** [comment]
Done.

**Pull request merged**
