### PR TITLE
issue-#41: Display correct status on Dot1x table

### PR DESCRIPTION
**Pull request by netniV**
This now displays the correct status in the Dot1x table listing

### CODE REVIEW

**Comment by jpobeda** [comment]
I don't see any changes after applying this commit.

**Comment by netniV** [comment]
Hmm, problem is that I have no data to see the change so when it all appeared to be working, it wasn't.  You will see a further commit that actually displays the new status I populated! 👍

**Comment by jpobeda** [comment]
I get this

```
Notice: Array to string conversion in /usr/share/cacti-1.1.21/plugins/mactrack/lib/mactrack_functions.php on line 2574

Notice: Array to string conversion in /usr/share/cacti-1.1.21/plugins/mactrack/lib/mactrack_functions.php on line 2574

Notice: Array to string conversion in /usr/share/cacti-1.1.21/plugins/mactrack/lib/mactrack_functions.php on line 2574

Notice: Array to string conversion in /usr/share/cacti-1.1.21/plugins/mactrack/lib/mactrack_functions.php on line 2574
```

And the table is actually showing "array"

image

**Comment by netniV** [comment]
That should be fixed now.  Hopefully for good :)

**Comment by jpobeda** [comment]
Now you're talking =O

image

**Comment by cigamit** [comment]
We should do more of this.  Cacti has moved the snmp cli to pretty much return everything numeric unless you ask for ASCII output.

**Pull request merged**
