### PR TITLE
mistake in mtdt table alias

### PR DESCRIPTION
**Pull request by Susanin63**
* without true in html_start_box div start with table tag
* incorect table name ailas

### CODE REVIEW

**Comment by TheWitness** [comment]
So, true means display as a table and not a div.  Are you sure you want that?  Means the html_end_box has to be changed too.

**Comment by TheWitness** [comment]
I merged in any case.

**Comment by Susanin63** [comment]
maybe the other way around?
изображение

without true we have table and error in html:

изображение

**Comment by Susanin63** [comment]
here the code
https://github.com/Cacti/cacti/blob/410bef458eb8673e3345440a4e67b9e14c9f8677/lib/html.php#L131-L135

**Pull request merged**
