### PR TITLE
Fix MacWatch, Sites - delete problem

### PR DESCRIPTION
**Pull request by ArturasJudickas**
Fix $i++; location in files mactrack_macwatch.php and mactrack_sites.php (problem delete records), Correcting visual in files mactrack_device.php and etc.

### CODE REVIEW

**Comment by TheWitness** [comment]
Although technically using the $i variable is not require, at least this will be consistent.  Fine and thanks for catching the two bugs.  

Before I commit, can you please update the CHANGELOG.md?

**Comment by ArturasJudickas** [comment]
This is the design syntax I found in the main cacti...
Did I update the CHANGELOG.md correctly?

**Comment by ArturasJudickas** [comment]
2020.10.22 04:30, TheWitness rašė:
> Although technically using the $i variable is not require, at least this 
> will be consistent. Fine and thanks for catching the two bugs.
This is the design syntax I found in the main cacti...


> 
> Before I commit, can you please update the CHANGELOG.md?
Did I update the CHANGELOG.md correctly?

**Comment by TheWitness** [comment]
No, please update the CHANGELOG.md.

**Comment by ArturasJudickas** [comment]
> No, please update the CHANGELOG.md.
> 
Does this mean that you have to write the solution text in CHANGELOG.md 
file?
#144: Fix MacWatch, Sites - delete problem

**Comment by TheWitness** [comment]
Yup as easy as that.  Just push that change into your repo and it'll appear in the pull like magic.

**Comment by TheWitness** [comment]
Yea, I know.  When I edit some of this very old code, I'm like "who the hell wrote that".  Most of time it turns out it's me.  That's how you evolve as you progress in your career.  Sometimes when you look back, you blush.

**Comment by TheWitness** [comment]
I'm going to merge this, but feel free to do another pull request with your changelog updates.  Thanks for helping out too!

**Pull request merged**
