### PR TITLE
added support for Trendnet and TP-LINK switches

### PR DESCRIPTION
**Pull request by ggomezsena**
added support for Trendnet TL2-G244, TP-LINK T2600G-28TS and TP-LINK T1600G-28TS-03 gigabit switches

### CODE REVIEW

**Comment by jpobeda** [comment]
Hey, thanks for pushing the PR. 

Can you please update the Copyrights to 2017?

**Comment by ggomezsena** [comment]
done!

**Comment by cigamit** [comment]
In the mactrack_vendors.php can you add something a bit more colorful on the 'who maintains', kind of 'we are community triven or something'.  After that, I'll merge.  Thanks for helping.  Looking forward to your update.

**Comment by ggomezsena** [comment]
i have paste your actual comments.
it is ok?
Thanks

**Pull request merged**
